name: Examples

on: [push, pull_request]

jobs:
  test-ubuntu:
    runs-on: Ubuntu-latest
    
    env:
      SHEPHERD_TOKEN: ${{ secrets.SHEPHERD_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

       name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rmarkdown

      - name: Execute
        run: |
          Rscript --vanilla -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Re-build examples' || echo Nothing has changed
          git push origin || echo "No changes to commit"
