name: Compile README.md

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      SHEPHERD_TOKEN: ${{ secrets.SHEPHERD_TOKEN}}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
        - name: latest
          cntr: dslabscl/dslab-covid-report:latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ matrix.cntr }}

      - name: Compilar
        run:  |
          docker run -v$(pwd):/home/report \
            -e SHEPHERD_TOKEN=$SHEPHERD_TOKEN\
            -w/home/report ${{ matrix.cntr }} \
            Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Re-build Rmarkdown files' || echo Nothing has changed
          git push origin || echo "No changes to commit"
